package com.greendao.bean;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table "DATA".
 */
public class Data {

    private Long id;
    /** Not-null value. */
    private String ShopName;
    private String freight;
    private String image;
    private String name;
    private String color;
    private String price;
    private String reduction;
    private String status;
    private String number;

    public Data() {
    }

    public Data(Long id) {
        this.id = id;
    }

    public Data(Long id, String ShopName, String freight, String image, String name, String color, String price, String reduction, String status, String number) {
        this.id = id;
        this.ShopName = ShopName;
        this.freight = freight;
        this.image = image;
        this.name = name;
        this.color = color;
        this.price = price;
        this.reduction = reduction;
        this.status = status;
        this.number = number;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getShopName() {
        return ShopName;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setShopName(String ShopName) {
        this.ShopName = ShopName;
    }

    public String getFreight() {
        return freight;
    }

    public void setFreight(String freight) {
        this.freight = freight;
    }

    public String getImage() {
        return image;
    }

    public void setImage(String image) {
        this.image = image;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getColor() {
        return color;
    }

    public void setColor(String color) {
        this.color = color;
    }

    public String getPrice() {
        return price;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    public String getReduction() {
        return reduction;
    }

    public void setReduction(String reduction) {
        this.reduction = reduction;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getNumber() {
        return number;
    }

    public void setNumber(String number) {
        this.number = number;
    }

}
